[Component]
    Components = [
        { Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Front End.frontend", Application = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"},
        { Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Front End.frontend", Application = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;Labor Day Sale;1.2.10.0"}
    ]    
    Version = "1.2.2"
    ChartName = "chart/frontend"
    DockerRepo = "quay.io/hipsterstore/frontend"
    GitUrl = "https://github.com/ortelius/store-frontend"
    HelmChart = "GLOBAL.HelmChart"