[Component]
    Components = [
       { Name = "GLOBAL.SF Tech.Online Store Company.Hipster Store.frontend", Application = "GLOBAL.SF Tech.Online Store Company.Hipster Store.Dev.Hipster Store;Labor Day Sale;1_2_10_2"}
    ]    
    Version = "1.2.2"
    ChartName = "chart/frontend"
    DockerRepo = "quay.io/hipsterstore/frontend"
    GitUrl = "https://github.com/ortelius/store-frontend"
    CustomAction = "GLOBAL.HelmChart"