apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "frontend.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}-external
spec:
  type: LoadBalancer
  selector:
    app: {{ include "frontend.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
